// src/components/Header.svelte
<script>
  import { Hamburger } from 'svelte-hamburgers'
  let open = false

  const navItems = [
    {
      href: 'https://www.klimatkollen.se/kallor-och-metod',
      label: 'Källor och metod',
    },
    { href: 'https://www.klimatkollen.se/om-oss', label: 'Om oss' },
    { href: '/blog', label: 'Insikter' },
    { href: 'https://klimatkollen.teamtailor.com/', label: 'Jobb' },
    { href: 'https://www.klimatkollen.se/in-english', label: 'In English' },
  ]
</script>

<header
  class="bg-black h-18 top-0 mb-1.5 w-full flex-shrink-0 pb-1.5 opacity-100 relative z-[2]"
>
  <div class="relative flex h-12 items-center justify-between px-4">
    <!-- Logo -->
    <div
      class="absolute left-1/2 top-1/2 z-[60] flex h-8 -translate-x-1/2 -translate-y-1/2"
    >
      <a
        href="https://klimatkollen.se"
        class="flex items-center"
        aria-label="Go to Klimatkollen homepage"
      >
        <img
          src="/klimatkollen_logo.svg"
          alt="Klimatkollen logga"
          width="150"
          class="pt-1"
        />
      </a>
    </div>
    <nav class="ml-auto hidden lg:flex h-[2rem] items-center gap-6">
      {#each navItems as item}
        <a
          href={item.href}
          class="relative text-white after:content-[''] after:block after:h-[2px] after:bg-white after:absolute after:left-0 after:bottom-[-2px] after:w-full after:scale-x-0 after:transition-transform after:duration-300 hover:after:scale-x-100"
        >
          {item.label}
        </a>
      {/each}
    </nav>
    <!-- Hamburger Button (Mobile) -->
    <div class="ml-auto block lg:hidden z-40">
      <Hamburger
        bind:open
        type="spin"
        --color="white"
        aria-label="Toggle menu"
        --layer-height="1px"
        --layer-width="22px"
      />
    </div>
  </div>

  <!-- Fullscreen Menu Overlay (Mobile View) -->
  {#if open}
    <!-- Background Overlay to hide content -->
    <div class="fixed inset-0 bg-black bg-opacity-75"></div>

    <!-- Fullscreen Menu (Nav Links) -->
    <div
      class="fullscreen-menu bg-black text-white fixed left-0 top-0 flex h-full w-full flex-col pl-4 pt-4"
    >
      <!-- Divider Line -->
      <hr class="mt-[48px] mb-4 h-1 bg-gray-350 border-0 w-full" />

      <!-- Navigation Links -->
      <nav class="flex flex-col gap-5">
        {#each navItems as item}
          <a href={item.href} class=" text-[1.5rem] hover:underline">
            {item.label}
          </a>
        {/each}
      </nav>
    </div>
  {/if}
</header>

// src/components/layout/Header.tsx
import { BarChart3, ChevronDown, Menu, X } from "lucide-react";
import { Link, useLocation, matchPath } from "react-router-dom";
import { cn } from "@/lib/utils";
import { useScrollDirection } from "@/hooks/useScrollDirection";
import { useState, useCallback } from "react";
import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarShortcut,
  MenubarTrigger,
} from "@/components/ui/menubar";
import { NewsletterPopover } from "../NewsletterPopover";

interface NavLink {
  label: string;
  icon?: JSX.Element;
  path: string;
  sublinks?: { label: string; path: string; shortcut?: string }[];
}

const NAV_LINKS: NavLink[] = [
  {
    label: "Företag",
    icon: <BarChart3 className="w-4 h-4" aria-hidden="true" />,
    path: "/companies",
  },
  {
    label: "Kommuner",
    icon: <BarChart3 className="w-4 h-4" aria-hidden="true" />,
    path: "/municipalities",
  },
  {
    path: "/about",
    label: "Om oss",
  },
  {
    path: "/insights",
    label: "Insikter",
  },
  {
    path: "/methodology",
    label: "Källor och metod",
  },
];

export function Header() {
  const location = useLocation();
  const { scrollDirection, scrollY } = useScrollDirection();
  const isMinimized = scrollDirection === "down" && scrollY > 100;
  const [menuOpen, setMenuOpen] = useState(false);
  const [isSignUpOpen, setIsSignUpOpen] = useState(false); // Newsletter popover state

  const toggleMenu = useCallback(() => setMenuOpen((prev) => !prev), []);

  return (
    <header
      className={cn(
        "fixed top-0 left-0 right-0 z-50 transition-all duration-300 py-2 md:py-0 bg-black-2 overflow-hidden",
        isMinimized ? "h-6" : "h-10",
        menuOpen && "h-full"
      )}
    >
      <div className="container mx-auto px-4 flex items-center justify-between py-0">
        {/* Logo */}
        <Link
          to="/"
          className={cn(
            "flex items-center gap-2 transition-all",
            isMinimized ? "scale-75 translate-y-[-6px]" : "translate-y-0"
          )}
        >
          Klimatkollen
        </Link>

        {/* Mobile Menu Toggle */}
        <button
          className={cn(
            "md:hidden text-white transition-transform duration-300",
            isMinimized ? "-translate-y-1 scale-90" : "scale-100"
          )}
          onClick={toggleMenu}
          aria-label={menuOpen ? "Close menu" : "Open menu"}
        >
          {menuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
        </button>

        {/* Desktop Navigation */}
        <nav
          className={cn(
            "hidden md:flex items-center gap-8 transition-all ml-auto",
            isMinimized
              ? "scale-90 translate-y-[-6px]"
              : "scale-100 translate-y-0"
          )}
        >
          <Menubar className="border-none bg-transparent">
            {NAV_LINKS.map((item) =>
              item.sublinks ? (
                <MenubarMenu key={item.label}>
                  <MenubarTrigger
                    aria-expanded={location.pathname.startsWith(item.path)}
                    className={cn(
                      "flex items-center gap-2 px-3 py-4 transition-colors transition-all",
                      location.pathname.startsWith(item.path)
                        ? "bg-black-1 text-white"
                        : "text-grey hover:text-white"
                    )}
                  >
                    {item.icon}
                    <span>{item.label}</span>
                    <ChevronDown className="w-4 h-4" aria-hidden="true" />
                  </MenubarTrigger>
                  <MenubarContent>
                    {item.sublinks.map((sublink) => (
                      <MenubarItem key={sublink.path}>
                        <Link
                          to={sublink.path}
                          className="flex items-center justify-between w-full"
                        >
                          {sublink.label}
                          {sublink.shortcut && (
                            <MenubarShortcut>
                              {sublink.shortcut}
                            </MenubarShortcut>
                          )}
                        </Link>
                      </MenubarItem>
                    ))}
                  </MenubarContent>
                </MenubarMenu>
              ) : (
                <Link
                  key={item.path}
                  to={item.path}
                  className={cn(
                    "flex items-center gap-2 p-3 transition-colors text-sm",
                    matchPath(item.path, location.pathname)
                      ? "bg-black-1 text-white"
                      : "text-grey hover:text-white",
                    isMinimized && "scale-75 -translate-x-4"
                  )}
                >
                  {item.icon}
                  <span>{item.label}</span>
                </Link>
              )
            )}
            {/* Adjust Spacing of Newsletter Button Separately */}
            <div className="ml-6">
              <NewsletterPopover
                isOpen={isSignUpOpen}
                setIsOpen={setIsSignUpOpen}
                buttonText="Nyhetsbrev"
              />
            </div>
          </Menubar>
        </nav>

        {/* Mobile Fullscreen Menu */}
        {menuOpen && (
          <div className="fixed inset-0 w-full h-full z-100 flex p-8 mt-12">
            <div className="flex flex-col gap-6 text-lg">
              {NAV_LINKS.map((link) => (
                <div key={link.path} className="flex flex-col">
                  <Link
                    to={link.path}
                    onClick={toggleMenu}
                    className="flex items-center gap-2"
                  >
                    {link.icon}
                    {link.label}
                  </Link>

                  {link.sublinks && (
                    <div className="flex flex-col gap-2 pl-4 mt-2">
                      {link.sublinks.map((sublink) => (
                        <Link
                          key={sublink.path}
                          to={sublink.path}
                          className="flex items-center gap-2 text-sm text-gray-400"
                        >
                          {sublink.label}
                        </Link>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </header>
  );
}
