// src/components/header.tsx
import React from 'react'

export function Header() {
  const navItems = [
    { href: 'https://www.klimatkollen.se/kallor-och-metod', label: 'Källor och metod' },
    { href: 'https://www.klimatkollen.se/om-oss', label: 'Om oss' },
    { href: 'https://klimatkollen.teamtailor.com/', label: 'Jobb' },
    { href: 'https://www.klimatkollen.se/in-english', label: 'In English' },
  ]

  return (
    <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container relative flex h-14 max-w-screen-2xl items-center justify-between">
        <div className="absolute inset-0 flex justify-center items-center">
          <a className="flex items-center space-x-2" href="https://www.klimatkollen.se/">
            <img src='/klimatkollen_logo.svg' alt='Klimatkollen logga' width={150} />
          </a>
        </div>
        <div className="flex flex-1 items-center justify-end space-x-2">
          <nav className="flex items-center gap-4 text-sm lg:gap-6">
            {navItems.map(item => (
              <a key={item.href} className="transition-colors hover:text-foreground/80 text-foreground/60" href={item.href}>
                {item.label}
              </a>
            ))}
          </nav>
        </div>
      </div>
    </header>
  )
}

// src/components/Header.svelte
<script>
  const baseURL = import.meta.env.DEV
    ? 'http://localhost:3000'
    : 'https://klimatkollen.se'

  const navItems = [
    {
      href: `https://www.klimatkollen.se/kallor-och-metod`,
      label: 'Källor och metod',
    },
    { href: `https://www.klimatkollen.se/om-oss`, label: 'Om oss' },
    { href: `https://klimatkollen.teamtailor.com/`, label: 'Jobb' },
    { href: `https://www.klimatkollen.se/in-english`, label: 'In English' },
  ]
</script>

<header
  class="bg-black h-18 top-0 mb-1.5 w-full flex-shrink-0 pb-1.5 opacity-100 relative z-[2]"
>
  <div class="relative flex h-12 items-center justify-between px-4">
    <div
      class="absolute left-1/2 top-1/2 z-[10] flex h-8 -translate-x-1/2 -translate-y-1/2"
    >
      <a
        href="https://klimatkollen.se"
        class="flex items-center"
        aria-label="Go to Klimatkollen homepage"
      >
        <img
          src="/klimatkollen_logo.svg"
          alt="Klimatkollen logga"
          width="150"
          class="pt-1"
        />
      </a>
    </div>
    <nav class="ml-auto hidden lg:flex h-[2rem] items-center gap-6">
      {#each navItems as item}
        <a
          href={item.href}
          class="relative text-white after:content-[''] after:block after:h-[2px] after:bg-white after:absolute after:left-0 after:bottom-[-2px] after:w-full after:scale-x-0 after:transition-transform after:duration-300 hover:after:scale-x-100"
        >
          {item.label}
        </a>
      {/each}
    </nav>
  </div>
</header>
